### PR TITLE
Fix npm 3.X issues

### PR DESCRIPTION
**Pull request by jansepar**

### CODE REVIEW

**Comment by jansepar** [comment]
Any update on this? Would love for this to get merged so I don't have to point my package.json to my custom fork!

**Comment by kennethormandy** [comment]
Hey, we don’t have access to publish a new release of this on npm, but you should be able to either trash your `node_modules` and reinstall to get the latest version of Harp (I think, since it’s set to `^` in the `package.json`) or you could install Harp as a `devDependency` as well alongside Grunt Harp, and I think that will get used instead.

Hopefully that helps, and let me know if not.

**Comment by jansepar** [comment]
Ah, is that due to the non-nested dependancies of npm 3? I'll give that a try!

**Comment by jansepar** [comment]
Looks like that doesn't work - I want to use a new version of harp, but because that doesn't match the version of harp that the latest grunt-harp wants, it installs the old harp as a nested dependancy. See https://docs.npmjs.com/how-npm-works/npm3.

**Pull request closed without merging**
